print("╔"+"═"*30+"╗")
print("║         Karakök ve Pi        ║")
print("║                              ║")
print("║      1-Karakök hesapla       ║")
print("║      2-Pi Hesapla            ║")
print("║                              ║")
print("║                              ║")
print("║                              ║")
print("║    Lütfen seçim yapınız :)   ║")
print("╚"+"═"*30+"╝")

